spring.application.name=crudSpringBootDemo
spring.datasource.url=jdbc:mysql://localhost:3306/student_crud_db
spring.datasource.username=root
spring.datasource.password=Jaikriti@1418
# Tell Hibernate to create tables automatically
spring.jpa.hibernate.ddl-auto=update

# Show SQL in terminal so you can see the CREATE TABLE statement
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Force database dialect if using Spring Boot 3+ / 4+
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect